TE PASO NUEVAS



-REDIMENSIONAR tamaño Y PROPORCIONES DE ELEMENTOS, TENER EN CUENTA FORMATO APP CELULAR Y WEB, VEO OBJETOS BOTONES EXAGERAMENTE GRANDE OCUPANDO MUCHO LUGAR.



-CUANDO SE REGISTRE UNA JUNTADA UNIFICAR EL PROCESO DE CANTIDAD DE KILOS CON SELECCION DE DESTINO, ES DECIR QUE AL REGISTRAR UNA JUNTADA SOLICITE SI O SI LUGAR DE DESTINO Y LCANTIDAD.



-APLICAR FUNCIONALIDADES PROFESIONALES SOBRE RECORDAR SELECCION AL REGISTRAR UNA COSECHA (PROBABLEMENTE EL FLUJO DE INFORMACION DE ESA PARTE VA A ESTAR ORDENADO CON MUCHOS INGRESOS A UN MISMO DESTINO, ESO HAY QUE APLICARLO EN TODOS LOS ELEMENTOS QUE LO QUEIERAN, QUE SEAN OBJETOS "INTELIGENTES" DONDE CONVEGA RECORDAR ALGO COMO EL EJEMPLO ANTERIOR.

-EN TOCK DE MERCADERIA, NO SE VE EL HISTORIAL DE INGRESOS DE MERCADERIA, TAMBIEN DEBERIA EXISTIR UNA OPCION DE EGRESO DE MERCADERIA, EL FILTRO TEMPORADA Y DEPOSITO DEBEN SER AUTOCOMPLETADOS CON LA TEMPORADA ACTUAL EN DEPOSITO ESTA BIEN QUE SE PERMITA SELECCIONAR, HAY QUE REGISTRAR TODOS LOS MOVIMIENTOS DE TODOS LOS PROCESOS Y PODER VER SU HISTORIAL (CREO QUE YA LO HABALMOS)



-CADA VEZ QUE SE HAGAN ACCIONES DENTRO DEL SISTEMA QUE SE REGISTREN MODIFIQUEN  EN LA BASE DE DATOS, DEBEN AUTOMATICAMENTE ACTUALIZARSE AUTOMATICAMENTE DESPUES DE EJECUTAR SU TAREA, HAY VECES QUE SE REQUIERE REACARGAR PAGINA PARA ACTUALIZAR NO PUEDE PASAR ESO



-SIMPLIFICAR LOS TABLEROS DE EL SISTEMA DONDE POR EJEMPLO EN EL MENU PERRSONAL NO NOS CHOQUE UN  FORMULARIO ENORME PARA AGREGAR UN NUEVO EMPLEADO, CUANDO PODRIA HABER UN BOTON QUE PERMITA VERLO OPCIONALMENTE, OTRA OPCION QUE SE VEAN EL HISTORIAL DE PERSONAL, ALTAS Y BAJAS Y MODIFICACIUONES, VER LISTA DE EMPLEADOS,  OPTIMIZAR ESPACIO Y ADAPTARLO ESTO A NUESTRO SISTEMA